addons:
  chrome: stable
language: node_js
node_js: '6'
before_install:
  - cd packages/change-detection/
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - npm start
deploy:
  provider: npm
  email: "angular-package@wwwdev.io"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: false
    branches:
      only:
      - change-detection
    repo: angular-package/angular-package
